version: "3"

services:
  backend:
    build: ./backend
    container_name: backend
    command:
      - ./backend/start.sh
    ports:
      - 8000:8010
    volumes:
      - ./backend/src/media:/backend/src/media
      - ./backend/src:/backend/src
    env_file:
      - ./backend/.env

  bot:
    build: ./bot
    container_name: bot
    ports:
      - 443:443
    volumes:
      - ./bot/app:/bot/app
    env_file:
      - ./bot/.env
    depends_on:
      - backend
