version: "3"

services:
  backend:
    build: ./backend
    container_name: backend
#    command:
#      - ./backend/start.sh
    ports:
      - 8000:8010
    volumes:
#      - static_content:/backend/src/static/
#      - media_content:/backend/src/media/
      - ./backend/src/media:/backend/src/media
      - ./backend/src:/backend/src
    env_file:
      - ./backend/.env

  bot:
    build: ./bot
    container_name: bot
    ports:
      - 443:443
    volumes:
      - ./bot/app:/bot/app
    env_file:
      - ./bot/.env
    depends_on:
      - backend
#      - nginx

#  nginx:
#    image: nginx
#    volumes:
#      - static_content:/backend/src/static/
#      - media_content:/backend/src/media/
#      - ./src/media:/backend/src/media
#      - ./nginx/default.conf:/etc/nginx/conf.d/default.conf
#    ports:
#      - 80:80
#      - 443:443
#    env_file:
#      - ./backend/.env
#    depends_on:
#      - backend


#volumes:
#  static_content: { }
#  media_content: { }

