# Generated by Django 4.1.7 on 2023-03-31 22:21

from django.conf import settings
from django.db import migrations, models
import django.db.models.deletion


class Migration(migrations.Migration):

    initial = True

    dependencies = [
        ('auth', '0012_alter_user_first_name_max_length'),
    ]

    operations = [
        migrations.CreateModel(
            name='Profile',
            fields=[
                ('user', models.OneToOneField(on_delete=django.db.models.deletion.CASCADE, primary_key=True, related_name='profile', serialize=False, to=settings.AUTH_USER_MODEL)),
                ('t_user_id', models.IntegerField(blank=True, null=True, verbose_name='Telegram user id')),
                ('t_username', models.CharField(blank=True, max_length=150, null=True, verbose_name='Telegram username')),
                ('photo', models.ImageField(blank=True, default='/empty_avatar.png', null=True, upload_to='profiles_avatars/%Y/%m/%d/', verbose_name='Avatar')),
            ],
        ),
    ]
