# Generated by Django 4.1.7 on 2023-03-30 20:14

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('accounts', '0001_initial'),
    ]

    operations = [
        migrations.AddField(
            model_name='profile',
            name='t_user_id',
            field=models.IntegerField(default=12, verbose_name='Telegram user id'),
            preserve_default=False,
        ),
        migrations.AddField(
            model_name='profile',
            name='t_username',
            field=models.CharField(default=1234687546, max_length=150, verbose_name='Telegram username'),
            preserve_default=False,
        ),
    ]
