# Generated by Django 4.1.7 on 2023-03-31 09:56

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('accounts', '0002_profile_t_user_id_profile_t_username'),
    ]

    operations = [
        migrations.AlterField(
            model_name='profile',
            name='t_user_id',
            field=models.IntegerField(null=True, verbose_name='Telegram user id'),
        ),
        migrations.AlterField(
            model_name='profile',
            name='t_username',
            field=models.CharField(max_length=150, null=True, verbose_name='Telegram username'),
        ),
    ]
