# Generated by Django 4.1.7 on 2023-03-31 10:54

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('accounts', '0003_alter_profile_t_user_id_alter_profile_t_username'),
    ]

    operations = [
        migrations.AddField(
            model_name='profile',
            name='photo',
            field=models.ImageField(blank=True, default='/empty_avatar.png', null=True, upload_to='profiles_avatars/%Y/%m/%d/', verbose_name='Avatar'),
        ),
        migrations.AlterField(
            model_name='profile',
            name='t_user_id',
            field=models.IntegerField(blank=True, null=True, verbose_name='Telegram user id'),
        ),
        migrations.AlterField(
            model_name='profile',
            name='t_username',
            field=models.CharField(blank=True, max_length=150, null=True, verbose_name='Telegram username'),
        ),
    ]
